# Set mesh resolution and extent
mesh:resolution 72 48 24
mesh:numblocks 1 1 1
mesh:extent 0.0 1.5 0.0 1.0 0.0 0.5

# Set time information
time:final 0.8
time:mindt 1.e-8
time:cfl 1.5
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename VortexGen
io:plotfreq 0.025
io:ckptfreq 25
io:verbose 1