# Set mesh resolution and extent
mesh:resolution 64 64 64
mesh:extent 0.0 1.0 0.0 1.0 0.0 1.0

# Set time information
time:initial 0.0
time:final 0.5
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 4000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.666666666666666
properties:wenothresh 20.0

# Output settings
output:datadir data
output:basename OrszagTang
output:plotfreq 50
