# Set mesh resolution and extent
mesh:resolution 512 512
mesh:extent 0.0 1.0 0.0 1.0

# Set time information
time:initial 0.0
time:final 1.0
time:initialdt 1.e-10
time:cfl 0.1
time:maxsteps 4000
time:atol 1.e-4
time:rtol 1.e-4

# Set stencil options
stencil:lfac 24
# stencil:bpow 2 commented out as default usually right

# Set fluid properties
properties:gamma 1.666666666666666
properties:wenothresh 10.0

# Output settings
output:datadir data
output:basename OrszagTang
output:plotfreq 40
