# Set mesh resolution and extent
mesh:resolution 256 8
mesh:extent 0.0 1.0 0.0 0.03125

# Set time information
time:initial 0.0
time:final 0.2
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 1000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:pdiconf ../../user/pdi_euler_2d.yml
output:datadir data
output:basename SodX
output:plotfreq 50
