# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1
mesh:extent -0.5 0.5 -0.5 0.5

# Set time information
time:initial 0.0
time:final 0.15
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 5000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 12

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 10.0

# Output settings
io:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename Rotor
io:plotfreq 50
io:ckptfreq 20
