# Set mesh resolution and extent
mesh:resolution 256 8 8
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 0.03125 0.0 0.03125

# Set time information
time:initial 0.0
time:final 1.e-8
time:mindt 1.e-8
time:cfl 1.e-8
time:maxsteps 2
time:atol 1.e-10
time:rtol 1.e-10

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 0.0
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_linadv_xdmf.yml
io:datadir data
io:basename DispRel
io:ckptfreq 1
io:verbose 2