# Set mesh resolution and extent
mesh:resolution 96 96 192
mesh:numblocks 1 1 1
mesh:extent 0.0 6.0 0.0 6.0 -6.0 6.0

# Set time information
time:initial 0.0
time:final 15.0
time:initialdt 1.e-8
time:cfl 2.0
time:maxsteps 50000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.6666666666666
eos:wenothresh 10.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename CircRayTay
io:plotfreq 100
io:ckptfreq 20
