# Set mesh resolution and extent
mesh:resolution 512 512 8
mesh:extent -0.5 0.5 -0.5 0.5 0.0 0.015625

# Set time information
time:initial 0.0
time:final 0.01
time:initialdt 1.e-14
time:cfl 0.75
time:maxsteps 5000

# Set stencil options
stencil:lfac 24
# stencil:bpow 2 commented out as default usually right

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 5.0

# Output settings
output:datadir data
output:basename MagBlast
output:plotfreq 40
