# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1
mesh:extent -10.0 10.0 -10.0 10.0

# Set time information
time:initial 0.0
time:final 20.0
time:initialdt 1.e-10
time:cfl 2.0
time:maxsteps 4000
time:atol 1.e-10
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666
eos:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename MagVort
io:plotfreq 100
io:ckptfreq 20
