# Set mesh resolution and extent
mesh:resolution 1024 1024 8
mesh:numblocks 1 1 1
mesh:extent -1.0 1.0 -1.0 1.0 0.0 0.03125

# Set time information
time:final 1.0
time:mindt 1.e-10
time:cfl 1.5
time:maxsteps 2000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.6666666666666
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename ZPinch
io:plotfreq 0.05
io:ckptfreq 25
io:verbose 1