# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1
mesh:extent -0.5 0.5 -0.5 0.5

# Set time information
time:final 0.15
time:mindt 1.e-10
time:cfl 1.25
time:maxsteps 5000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename Rotor8W
io:plotfreq 0.01
io:ckptfreq 200
io:verbose 1
