# Set mesh resolution and extent
mesh:resolution 768 2304
mesh:numblocks 1 1 1
mesh:extent 0.0 0.5 0.0 1.5

# Set time information
time:initial 0.0
time:final 0.04
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 20000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 12

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename AstroJetLD
io:plotfreq 25
io:ckptfreq 20
