# Set mesh resolution and extent
mesh:resolution 96 96 96
mesh:extent 0.0 6.2831853072 0.0 6.2831853072 0.0 6.2831853072

# Set time information
time:initial 0.0
time:final 10.75
time:initialdt 1.e-10
time:cfl 0.75
time:maxsteps 6000

# Set stencil options
stencil:lfac 24
# stencil:bpow 2 commented out as default usually right

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 30.0

# Output settings
output:datadir data
output:basename TaylorGreen
output:plotfreq 100
