# Set mesh resolution and extent
mesh:resolution 256 256
mesh:extent -1.0 1.0 -1.0 1.0

# Set time information
time:initial 0.0
time:final 0.8
time:initialdt 1.e-10
time:cfl 0.4
time:maxsteps 1000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.66666666666
properties:wenothresh 2.0

# Output settings
output:pdiconf ../../user/pdi_srhydro_xdmf.yml
output:datadir data
output:basename SRRiem
output:plotfreq 10
