# Set mesh resolution and extent
mesh:resolution 256 256
mesh:numblocks 1 1
mesh:extent -1.0 1.0 -1.0 1.0

# Set time information
time:initial 0.0
time:final 0.8
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 1000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
properties:gamma 1.66666666666666
properties:wenothresh -1.0

# Output settings
io:pdiconf ../../user/pdi_srhydro_xdmf.yml
io:datadir data
io:basename SRRiem
io:plotfreq 100
io:ckptfreq 20
