# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1
mesh:extent 0.0 0.3 0.0 0.3

# Set time information
time:initial 0.0
time:final 2.5
time:mindt 1.e-10
time:cfl 1.25
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-4

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename Implosion
io:plotfreq 0.1
io:ckptfreq 1000
io:verbose 1
