# Set mesh resolution and extent
mesh:resolution 112 112 112
mesh:numblocks 1 1 1
mesh:extent 0.0 0.3 0.0 0.3 0.0 0.3

# Set time information
time:initial 0.0
time:final 2.5
time:mindt 1.e-10
time:cfl 1.0
time:maxsteps 10000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename Implosion
io:plotfreq 0.25
io:ckptfreq 20
io:verbose 1
