# Set mesh resolution and extent
mesh:resolution 128 128 8
mesh:extent -10.0 10.0 -10.0 10.0 0.0 1.25

# Set time information
time:initial 0.0
time:final 20.0
time:initialdt 1.e-10
time:cfl 0.05
time:maxsteps 2500
time:atol 1.e-5
time:rtol 1.e-5

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 30.0

# Output settings
output:datadir data
output:basename IsenVort
output:plotfreq 40
