# Set mesh resolution and extent
mesh:resolution 64 32 32
mesh:numblocks 1 1 1
mesh:extent 0.0 3.0 0.0 1.5 0.0 1.5

# Set time information
time:initial 0.0
time:final 2.0
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 4000
time:atol 1.e-8
time:rtol 1.e-6

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666
eos:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename CircAlfven
io:plotfreq 100
io:ckptfreq 20
