# Set mesh resolution and extent
mesh:resolution 256 128
mesh:numblocks 1 1
mesh:extent -1.0 1.0 -0.5 0.5

# Set time information
time:final 1.0
time:mindt 1.e-10
time:cfl 1.5
time:maxsteps 4000
time:atol 1.e-5
time:rtol 1.e-4

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename FieldLoop
io:plotfreq 0.1
io:ckptfreq 20
io:verbose 1
