# Set mesh resolution and extent
mesh:resolution 256 256 8
mesh:extent 0.0 1.0 0.0 1.0 0.0 1.0

# Set time information
time:initial 0.0
time:final 0.06
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 10000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.666666666666666
properties:wenothresh 20.0

# Output settings
output:datadir data
output:basename MagShockBubble
output:plotfreq 50
