# Set mesh resolution and extent
mesh:resolution 128 384
mesh:extent 0.0 0.5 0.0 1.5

# Set time information
time:initial 0.0
time:final 0.002
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 20000
time:atol 1.e-5
time:rtol 1.e-5

# Set stencil options
stencil:lfac 24
# stencil:bpow 2 commented out as default usually right

# Set fluid properties
properties:gamma 1.4
properties:wenothresh -1.0

# Output settings
output:datadir data
output:basename AstroJetHD
output:plotfreq 50
