# Set mesh resolution and extent
mesh:resolution 256 256
mesh:numblocks 1 1
mesh:extent 0.0 1.0 0.0 1.0

# Set time information
time:initial 0.0
time:final 0.8
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 2500
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 12

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 10.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename Riem
io:plotfreq 50
io:ckptfreq 20
