# Set mesh resolution and extent
mesh:resolution 256 128
mesh:extent -1.0 1.0 -0.5 0.5

# Set time information
time:initial 0.0
time:final 1.0
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 4000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
output:datadir data
output:basename FieldLoop
output:plotfreq 50
