# Set mesh resolution and extent
mesh:resolution 256 128
mesh:numblocks 1 1
mesh:extent -1.0 1.0 -0.5 0.5

# Set time information
time:initial 0.0
time:final 1.0
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 4000
time:atol 1.e-5
time:rtol 1.e-4

# Set stencil options
stencil:lfac 12

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename FieldLoop
io:plotfreq 20
io:ckptfreq 20
