# Set mesh resolution and extent
mesh:resolution 256 256 8
mesh:numblocks 1 1 1
mesh:extent -1.0 1.0 -1.0 1.0 0.0 0.125

# Set time information
time:initial 0.0
time:final 1.0
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 2500
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename BuchHelz
io:plotfreq 50
io:ckptfreq 20
