# Set mesh resolution and extent
mesh:resolution 128 128 128
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 1.0 0.0 1.0

# Set time information
time:final 1.0
time:mindt 1.e-10
time:cfl 1.25
time:maxsteps 4000
time:atol 1.e-4
time:rtol 1.e-4

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666666
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename OrszagTang
io:plotfreq 0.25
io:ckptfreq 200
io:verbose 1