# Set mesh resolution and extent
mesh:resolution 32 32 32
mesh:numblocks 1 1 1
mesh:extent -5.0 5.0 -5.0 5.0 -5.0 5.0

# Set time information
time:final 10.0
time:mindt 1.e-10
time:cfl 1.5
time:maxsteps 4000
time:atol 1.e-4
time:rtol 1.e-2

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename MagVort
io:plotfreq 0.5
io:ckptfreq 20
io:verbose 1
