# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1
mesh:extent -6.0 6.0 -6.0 6.0

# Set time information
time:final 15.0
time:mindt 1.e-8
time:cfl 1.5
time:maxsteps 50000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.6666666666666
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename CircRayTay
io:plotfreq 0.5
io:ckptfreq 200
io:verbose 1
