# Set mesh resolution and extent
mesh:resolution 96 192 96
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 2.0 0.0 1.0

# Set time information
time:initial 0.0
time:final 5.0
time:initialdt 1.e-8
time:cfl 3.0
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:pdiconf ../../user/pdi_euler_xdmf.yml
output:datadir data
output:basename KelvHelm
output:plotfreq 50
