# Set mesh resolution and extent
mesh:resolution 8 400 8
mesh:numblocks 1 1 1
mesh:extent 0.0 0.02 0.0 1.0 0.0 0.02

# Set time information
time:final 0.4
time:mindt 1.e-10
time:cfl 1.5
time:maxsteps 1000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666666
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_srhydro_xdmf.yml
io:datadir data
io:basename SRShockTube
io:plotfreq 0.05
io:ckptfreq 20
io:verbose 1