# Set mesh resolution and extent
mesh:resolution 96 96 96
mesh:extent 0.0 0.5 0.0 0.5 0.0 0.5

# Set time information
time:initial 0.0
time:final 0.2
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 1000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:datadir data
output:basename Sedov
output:plotfreq 50
