# Set mesh resolution and extent
mesh:resolution 4000 4 4
mesh:numblocks 1 1 1
mesh:extent 0.0 9.0 0.0 0.009 0.0 0.009

# Set time information
time:final 1.8
time:mindt 1.e-10
time:cfl 0.75
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-4

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename ShuOsher
io:plotfreq 0.1
io:ckptfreq 200
io:verbose 1