# Set mesh resolution and extent
mesh:resolution 512 512
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 1.0

# Set time information
time:final 0.06
time:mindt 1.e-10
time:cfl 1.0
time:maxsteps 10000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.666666666666666
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename MagShockBubble
io:plotfreq 0.005
io:ckptfreq 200
io:verbose 1
