# Set mesh resolution and extent
mesh:resolution 8 8 256
mesh:extent 0.0 0.0625 0.0 0.0625 -1.0 1.0

# Set time information
time:initial 0.0
time:final 0.2
time:initialdt 1.e-10
time:cfl 0.5
time:maxsteps 1000

# Set stencil options
stencil:lfac 24
# stencil:bpow 2 commented out as default usually right

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:datadir data
output:basename SodZ
output:plotfreq 40
