# Set mesh resolution and extent
mesh:resolution 64 128 128
mesh:numblocks 1 1 1
mesh:extent -0.5 0.5 0.0 2.0 -1.0 1.0

# Set time information
time:initial 0.0
time:final 15.0
time:initialdt 1.e-8
time:cfl 2.0
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename FluxRope
io:plotfreq 50
io:ckptfreq 20
