# Set mesh resolution and extent
mesh:resolution 400 4 4
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 0.01 0.0 0.01

# Set time information
time:final 0.038
time:mindt 1.e-10
time:cfl 1.0
time:maxsteps 50000
time:atol 1.e-1
time:rtol 1.e-1

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename BlastWaves
io:plotfreq 0.001
io:ckptfreq 1000
io:verbose 1
