# Set mesh resolution and extent
mesh:resolution 96 96 96
mesh:numblocks 1 1 1
mesh:extent 0.0 0.5 0.0 0.5 0.0 0.5

# Set time information
time:initial 0.0
time:final 0.2
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 1000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 20.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename Sedov
io:plotfreq 50
io:ckptfreq 20
