# Set mesh resolution and extent
mesh:resolution 128 128 128
mesh:numblocks 1 1 1
mesh:extent 0.0 0.5 0.0 0.5 0.0 0.5

# Set time information
time:final 0.4
time:mindt 1.e-10
time:cfl 1.25
time:maxsteps 1000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.4
eos:wenothresh 1.0

# Output settings
io:pdiconf ../../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename Sedov
io:plotfreq 0.01
io:ckptfreq 200
io:verbose 1
