# Set mesh resolution and extent
mesh:resolution 800 8 8
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 0.01 0.0 0.01

# Set time information
time:initial 0.0
time:final 0.1
time:mindt 1.e-10
time:cfl 1.0
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 2.0
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../../user/pdi_mhd_glm_xdmf.yml
io:datadir data
io:basename BrioWuX
io:plotfreq 0.01
io:ckptfreq 50
io:verbose 1
