# Space dimension of problem
DIM ?= 3
# Stencil radius (2-4)
STENRAD ?= 2
# Number of Gauss-Legendre points on faces (1-9)
NUMQUAD ?= 3
# Use linearized primitive reconstruction (yes/no)
PRIMREC ?= yes

INCLUDE_PATH += $(PWD)
include ../Make.kfvm
