# Set mesh resolution and extent
mesh:resolution 64 64 64
mesh:extent -1.0 1.0 -1.0 1.0 -1.0 1.0

# Set time information
time:initial 0.0
time:final 0.53
time:initialdt 1.e-10
time:cfl 0.1
time:maxsteps 2500
time:atol 1.e-4
time:rtol 1.e-4

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.4
properties:wenothresh 20.0

# Output settings
output:datadir data
output:basename Riem
output:plotfreq 50
