# Set mesh resolution and extent
mesh:resolution 1120 384
mesh:numblocks 1 1
mesh:extent 0.0 35.0 0.0 12.0

# Set time information
time:initial 0.0
time:final 80.0
time:initialdt 1.e-10
time:cfl 1.0
time:maxsteps 10000
time:atol 1.e-3
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
eos:gamma 1.66666666666666
eos:wenothresh -1.0

# Output settings
io:pdiconf ../../user/pdi_srhydro_xdmf.yml
io:datadir data
io:basename AstroJetSR
io:plotfreq 100
io:ckptfreq 20
