# Set mesh resolution and extent
mesh:resolution 384 384
mesh:extent 0.0 15.0 0.0 15.0

# Set time information
time:initial 0.0
time:final 2.5
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 10000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 24

# Set fluid properties
properties:gamma 1.666666666666666
properties:wenothresh 10.0

# Output settings
output:pdiconf ../../user/pdi_euler_xdmf.yml
output:datadir data
output:basename CircImplosion
output:plotfreq 50
