# Stencil radius (2-4)
STENRAD ?= 2
# Number of Gauss-Legendre points on faces (1-9)
NUMGAUSS ?= 3
# Use linearized primitive reconstruction (yes/no)
PRIMREC ?= yes

INCLUDE_PATH += $(PWD)
SOURCES += ProblemSetup.cpp
include ../Make.kfvm
