# Set mesh resolution and extent
mesh:resolution 256 8 8
mesh:numblocks 1 1 1
mesh:extent 0.0 1.0 0.0 0.03125 0.0 0.03125

# Set time information
time:initial 0.0
time:final 0.2
time:initialdt 1.e-10
time:cfl 1.5
time:maxsteps 1000
time:atol 1.e-4
time:rtol 1.e-3

# Set stencil options
stencil:lfac 5

# Set fluid properties
properties:gamma 1.4
properties:wenothresh -1.0

# Output settings
io:pdiconf ../../user/pdi_euler_xdmf.yml
io:datadir data
io:basename SodX
io:plotfreq 100
io:ckptfreq 20
